### ISSUE TITLE
使用gcc编译代码会报错

### ISSUE THREAD

**Issue by SummerGaoPlus** [seriyps/ecaptcha#1]
cc mk_font.c -I/usr/include/freetype2 -I/usr/include/libpng15  -lfreetype   -lm -o mk_font
mk_font.c: In function â:
mk_font.c:49:3: error: â loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < ctx->num_chars; i++) {
   ^
mk_font.c:49:3: note: use option -std=c99 or -std=gnu99 to compile your code
mk_font.c: In function â:
mk_font.c:62:3: error: â loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < ctx->num_fonts; i++) {
   ^
mk_font.c: In function â:
mk_font.c:90:3: error: â loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < y_shift; i++)
   ^
mk_font.c:92:3: error: â loop initial declarations are only allowed in C99 mode
   for (size_t row = 0; row < bitmap->rows; row++) {
   ^
mk_font.c:94:5: error: â loop initial declarations are only allowed in C99 mode
     for (size_t col = 0; col < bitmap->width; col++) {
     ^
mk_font.c: In function â:
mk_font.c:147:3: error: â loop initial declarations are only allowed in C99 mode
   for (int i = 1; i < argc; i++) {
   ^
mk_font.c:157:5: error: â loop initial declarations are only allowed in C99 mode
     for (char *p = ctx.name; *p; ++p)
     ^
mk_font.c:175:5: error: â loop initial declarations are only allowed in C99 mode
     for (int n = 0; n < ctx.num_chars; n++) {
     ^
make[1]: *** [mk_font] Error 1

**Comment by seriyps** [comment]
Hi, thanks! I will have a look. Btw, what version of GCC you use? `gcc --version`

**Comment by SummerGaoPlus** [comment]
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC)

**Comment by SummerGaoPlus** [comment]
Thanks, problem solved. The reason is that my gcc version is too low, upgrade to gcc version 9.3.1 and compile normally.

**Comment by SummerGaoPlus** [comment]
Thanks, problem solved. The reason is that my gcc version is too low, upgrade to gcc version 9.3.1 and compile normally.
